name: DevSecOps Pipeline

on:
  push:
  pull_request:
  workflow_dispatch: {}

jobs:

  # 📥 Preparación
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  # 🔍 SAST
  sast:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Semgrep
        run: pip install semgrep

      - name: Ejecutar SAST
        run: semgrep --config=auto --error

      # - name: Subir reporte SAST
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: semgrep-report
      #     path: semgrep-report.json
      
  # 🛡️ SCA (Software Composition Analysis)
  sca:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar pip-audit
        run: pip install pip-audit

      - name: Ejecutar SCA con pip-audit
        # -r: analiza el archivo de requerimientos
        # --local: ignora paquetes instalados en el sistema global (opcional)
        # --format: puedes usar 'columns', 'json', o 'cyclonedx'
        run: pip-audit -r requirements.txt
        
  # 🔑 Secret Scanning
  secret-scan:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v4

      - name: Ejecutar Gitleaks
        uses: gitleaks/gitleaks-action@v2
